/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */
import type { ExpandRequestSourceNodeId } from './expandRequestSourceNodeId';

export interface ExpandRequest {
  /**
   * The concept to expand
   * @minLength 1
   * @maxLength 200
   */
  topic: string;
  /** ID of existing node to connect new concepts to. If not provided, creates edges from topic. */
  source_node_id?: ExpandRequestSourceNodeId;
  /**
   * Previous concepts in the exploration path
   * @maxItems 50
   */
  context?: string[];
  /**
   * Number of related concepts to generate
   * @minimum 1
   * @maximum 20
   */
  num_expansions?: number;
}
