/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */
import type { GraphNode } from './graphNode';
import type { GraphEdge } from './graphEdge';

export interface ExpandResponse {
  nodes: GraphNode[];
  edges: GraphEdge[];
  reasoning: string;
}
