/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

/**
 * ID of existing node to connect new concepts to. If not provided, creates edges from topic.
 */
export type ExpandRequestSourceNodeId = string | null;
