/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

export type GraphNodeType = typeof GraphNodeType[keyof typeof GraphNodeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GraphNodeType = {
  root: 'root',
  generated: 'generated',
} as const;
