/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */
import type { GraphNodeType } from './graphNodeType';
import type { GraphNodeReason } from './graphNodeReason';

export interface GraphNode {
  /**
   * Unique kebab-case identifier
   * @minLength 1
   * @maxLength 100
   */
  id: string;
  /**
   * Human-readable label
   * @minLength 1
   * @maxLength 200
   */
  label: string;
  type: GraphNodeType;
  /** Why this concept relates */
  reason?: GraphNodeReason;
}
