/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseStatus } from './healthResponseStatus';
import type { HealthResponseServices } from './healthResponseServices';

export interface HealthResponse {
  status: HealthResponseStatus;
  version?: string;
  services?: HealthResponseServices;
}
