/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

export type HealthResponseStatus = typeof HealthResponseStatus[keyof typeof HealthResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthResponseStatus = {
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy',
} as const;
