/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

export interface SeedRequest {
  /**
   * The seed topic to start with
   * @minLength 1
   * @maxLength 200
   */
  topic: string;
}
