/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */
import type { GraphNode } from './graphNode';

export interface SeedResponse {
  node: GraphNode;
  reasoning: string;
}
