/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

export interface SimilarityRequest {
  /**
   * The topic to check similarity for
   * @minLength 1
   * @maxLength 200
   */
  topic: string;
  /**
   * Existing node labels to compare against
   * @minItems 1
   * @maxItems 50
   */
  context: string[];
  /**
   * Similarity threshold (0-1). Below this = unrelated
   * @minimum 0
   * @maximum 1
   */
  threshold?: number;
}
