/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

/**
 * The context item most similar to the topic
 */
export type SimilarityResponseClosestMatch = string | null;
