/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */
import type { SimilarityResponseClosestMatch } from './similarityResponseClosestMatch';
import type { SimilarityResponseSuggestedAction } from './similarityResponseSuggestedAction';

export interface SimilarityResponse {
  /** Whether the topic is semantically related to context */
  is_related: boolean;
  /**
   * Highest similarity score found
   * @minimum 0
   * @maximum 1
   */
  similarity_score: number;
  /** The context item most similar to the topic */
  closest_match?: SimilarityResponseClosestMatch;
  /** Recommended action: expand existing graph or create new root */
  suggested_action: SimilarityResponseSuggestedAction;
}
