/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gnosis API
 * Real-time semantic mind-mapping engine
 * OpenAPI spec version: 1.0.0
 */

/**
 * Recommended action: expand existing graph or create new root
 */
export type SimilarityResponseSuggestedAction = typeof SimilarityResponseSuggestedAction[keyof typeof SimilarityResponseSuggestedAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SimilarityResponseSuggestedAction = {
  expand: 'expand',
  new_root: 'new_root',
} as const;
